In [82]:
import pandas as pd

In [98]:
df = pd.read_csv("Kenji16.csv")
df.head()

      Area        X        Y   Perim. classification reference   SE
0  1  1354  801.383   40.203  136.225              -         -  NaN
1  2  1716  330.383  150.382  154.853            bud         3  NaN
2  3  2691  285.618  169.953  194.409         mother         2  NaN
3  4  2668   465.47   184.26  192.995         mother        13  1.0
4  5  1753  238.367  180.879  156.853             un         -  1.0

In [84]:
df['SE'] = df['SE'].fillna(0)
df.head()

      Area        X        Y   Perim. classification reference   SE
0  1  1354  801.383   40.203  136.225              -         -  0.0
1  2  1716  330.383  150.382  154.853            bud         3  0.0
2  3  2691  285.618  169.953  194.409         mother         2  0.0
3  4  2668   465.47   184.26  192.995         mother        13  1.0
4  5  1753  238.367  180.879  156.853             un         -  1.0

In [85]:
df.columns

Index([' ', 'Area', 'X', 'Y', 'Perim.', 'classification', 'reference', 'SE'], dtype='object')

In [86]:
df.set_index(' ', inplace=True)

In [87]:
df.head()

   Area        X        Y   Perim. classification reference   SE

1  1354  801.383   40.203  136.225              -         -  0.0
2  1716  330.383  150.382  154.853            bud         3  0.0
3  2691  285.618  169.953  194.409         mother         2  0.0
4  2668   465.47   184.26  192.995         mother        13  1.0
5  1753  238.367  180.879  156.853             un         -  1.0

In [88]:
def ref_peri(number):
    if number == '-':
        return number
    else:
        return df['Perim.'].iloc[int(number)-1]

In [89]:
df['ref_peri'] = df['reference'].apply(ref_peri)

In [90]:
def md_ratio(row):
    if (row['classification']=='-') | (row['classification']=='un'):
        return '-'
    elif row['classification']=='bud':
        return row['Perim.'] / float(row['ref_peri'])
    else:
        return float(row['ref_peri']) / row['Perim.']

In [91]:
df['ratio'] = df.apply(md_ratio, axis=1)

In [92]:
df

,Area,X,Y,Perim.,classification,reference,SE,ref_peri,ratio
,,,,,,,,,
1,1354,801.383,40.203,136.225,-,-,0.0,-,-
2,1716,330.383,150.382,154.853,bud,3,0.0,194.409,0.796532
3,2691,285.618,169.953,194.409,mother,2,0.0,154.853,0.796532
4,2668,465.47,184.26,192.995,mother,13,1.0,140.711,0.729091
5,1753,238.367,180.879,156.853,un,-,1.0,-,-
6,2245,747.376,192.168,177.681,bud,7,0.0,220.894,0.804372
7,3493,692.775,204.043,220.894,mother,6,0.0,177.681,0.804372
8,1730,362.937,226.15,156.267,bud,10,0.0,202.894,0.77019
9,2314,173.639,229.989,178.510,mother,12,0.0,66.184,0.370758
10,2951,414.881,235.886,202.894,mother,8,0.0,156.267,0.77019
11,1900,123.047,231.671,163.782,mother,14,0.0,160.752,0.9815
12,309,209.659,219.316,66.184,bud,9,0.0,178.51,0.370758
13,1421,466.974,234.964,140.711,bud,4,0.0,192.995,0.729091
14,1799,114.453,274.014,160.752,bud,15,1.0,166.267,0.96683
15,1940,147.366,306.655,166.267,mother,14,0.0,160.752,0.96683
16,1770,152.006,348.932,158.953,bud,17,0.0,228.794,0.694743
17,3758,98.344,363.147,228.794,mother,16,1.0,158.953,0.694743
18,1438,540.643,390.03,143.681,bud,19,0.0,220.309,0.652179
19,3485,499.584,420.454,220.309,mother,18,0.0,143.681,0.652179
20,2518,585.398,460.482,188.894,mother,23,0.0,154.853,0.819788
21,3213,245.692,475.974,213.966,mother,24,0.0,209.622,0.979698
22,2577,66.503,489.178,188.752,un,-,1.0,-,-
23,1730,554.903,498.024,154.853,bud,20,0.0,188.894,0.819788
24,3101,190.109,511.344,209.622,bud,21,0.0,213.966,0.979698
25,1512,602.499,503.22,146.953,bud,26,0.0,238.794,0.615397
26,3990,656.579,513.941,238.794,mother,25,0.0,146.953,0.615397
27,3658,847.87,529.496,226.693,bud,30,0.0,213.723,1.060686
28,2088,254.552,529.237,170.267,mother,29,0.0,105.154,0.617583
29,785,217.853,545.987,105.154,bud,28,0.0,170.267,0.617583
30,3247,902.867,562.506,213.723,mother,27,0.0,226.693,1.060686
31,3201,633.481,569.625,213.480,mother,32,0.0,141.296,0.66187
32,1359,585.142,566.089,141.296,bud,31,0.0,213.48,0.66187
33,2868,560.303,604.542,202.551,mother,36,0.0,148.51,0.733198
34,1224,878.436,604.815,133.196,bud,37,0.0,165.338,0.805598
35,1443,429.596,621.135,143.439,bud,38,0.0,188.894,0.759362
36,1578,603.761,629.853,148.510,bud,33,0.0,202.551,0.733198
37,1947,901.882,639.78,165.338,mother,34,0.0,133.196,0.805598
38,2505,387.67,645.222,188.894,mother,35,0.0,143.439,0.759362
39,2537,443.48,667.131,188.510,mother,42,0.0,148.024,0.785232
40,3586,686.509,673.696,224.551,un,-,0.0,-,-
41,2791,555.445,699.584,195.924,mother,43,0.0,170.61,0.870797
42,1538,401.41,693.826,148.024,bud,39,0.0,188.51,0.785232
43,2101,504.161,706.89,170.610,bud,41,0.0,195.924,0.870797
44,2809,446.185,720.651,197.581,mother,45,1.0,196.652,0.995298
45,2735,387.728,739.604,196.652,bud,44,1.0,197.581,0.995298
46,2943,190.225,756.484,202.551,mother,47,0.0,200.309,0.988931
47,2875,139.532,786.914,200.309,bud,46,0.0,202.551,0.988931
48,1750,823.994,843.921,158.953,mother,49,0.0,124.125,0.780891
49,1101,862.178,859.147,124.125,bud,48,0.0,158.953,0.780891
50,1921,829.45,887.644,163.539,un,-,0.0,-,-
51,2011,228.806,962.739,169.338,-,-,0.0,-,-
52,1,-,-,1.000,bud,11,0.0,163.782,0.006106

In [93]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 52 entries, 1 to 52
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Area            52 non-null     int64
 1   X               52 non-null     object
 2   Y               52 non-null     object
 3   Perim.          52 non-null     float64
 4   classification  52 non-null     object
 5   reference       52 non-null     object
 6   SE              52 non-null     float64
 7   ref_peri        52 non-null     object
 8   ratio           52 non-null     object
dtypes: float64(2), int64(1), object(6)
memory usage: 4.1+ KB

In [94]:
def classification(row):
    if row['classification']=='-':
        return '-'
    elif row['classification']=='un':
        return 'no_bud'
    elif (row['classification']=='bud') & (float(row['ratio'])<=0.5):
        return 'small_daughter'
    elif (row['classification']=='bud') & (float(row['ratio'])>0.5):
        return 'large_daughter'
    elif (row['classification']=='mother') & (float(row['ratio'])<=0.5):
        return 'small_mother'
    else:
        return 'large_mother'

In [95]:
df['five_class'] = df.apply(classification, axis=1)

In [97]:
df

,Area,X,Y,Perim.,classification,reference,SE,ref_peri,ratio,five_class
,,,,,,,,,,
1,1354,801.383,40.203,136.225,-,-,0.0,-,-,-
2,1716,330.383,150.382,154.853,bud,3,0.0,194.409,0.796532,large_daughter
3,2691,285.618,169.953,194.409,mother,2,0.0,154.853,0.796532,large_mother
4,2668,465.47,184.26,192.995,mother,13,1.0,140.711,0.729091,large_mother
5,1753,238.367,180.879,156.853,un,-,1.0,-,-,no_bud
6,2245,747.376,192.168,177.681,bud,7,0.0,220.894,0.804372,large_daughter
7,3493,692.775,204.043,220.894,mother,6,0.0,177.681,0.804372,large_mother
8,1730,362.937,226.15,156.267,bud,10,0.0,202.894,0.77019,large_daughter
9,2314,173.639,229.989,178.510,mother,12,0.0,66.184,0.370758,small_mother
10,2951,414.881,235.886,202.894,mother,8,0.0,156.267,0.77019,large_mother
11,1900,123.047,231.671,163.782,mother,14,0.0,160.752,0.9815,large_mother
12,309,209.659,219.316,66.184,bud,9,0.0,178.51,0.370758,small_daughter
13,1421,466.974,234.964,140.711,bud,4,0.0,192.995,0.729091,large_daughter
14,1799,114.453,274.014,160.752,bud,15,1.0,166.267,0.96683,large_daughter
15,1940,147.366,306.655,166.267,mother,14,0.0,160.752,0.96683,large_mother
16,1770,152.006,348.932,158.953,bud,17,0.0,228.794,0.694743,large_daughter
17,3758,98.344,363.147,228.794,mother,16,1.0,158.953,0.694743,large_mother
18,1438,540.643,390.03,143.681,bud,19,0.0,220.309,0.652179,large_daughter
19,3485,499.584,420.454,220.309,mother,18,0.0,143.681,0.652179,large_mother
20,2518,585.398,460.482,188.894,mother,23,0.0,154.853,0.819788,large_mother
21,3213,245.692,475.974,213.966,mother,24,0.0,209.622,0.979698,large_mother
22,2577,66.503,489.178,188.752,un,-,1.0,-,-,no_bud
23,1730,554.903,498.024,154.853,bud,20,0.0,188.894,0.819788,large_daughter
24,3101,190.109,511.344,209.622,bud,21,0.0,213.966,0.979698,large_daughter
25,1512,602.499,503.22,146.953,bud,26,0.0,238.794,0.615397,large_daughter
26,3990,656.579,513.941,238.794,mother,25,0.0,146.953,0.615397,large_mother
27,3658,847.87,529.496,226.693,bud,30,0.0,213.723,1.060686,large_daughter
28,2088,254.552,529.237,170.267,mother,29,0.0,105.154,0.617583,large_mother
29,785,217.853,545.987,105.154,bud,28,0.0,170.267,0.617583,large_daughter
30,3247,902.867,562.506,213.723,mother,27,0.0,226.693,1.060686,large_mother
31,3201,633.481,569.625,213.480,mother,32,0.0,141.296,0.66187,large_mother
32,1359,585.142,566.089,141.296,bud,31,0.0,213.48,0.66187,large_daughter
33,2868,560.303,604.542,202.551,mother,36,0.0,148.51,0.733198,large_mother
34,1224,878.436,604.815,133.196,bud,37,0.0,165.338,0.805598,large_daughter
35,1443,429.596,621.135,143.439,bud,38,0.0,188.894,0.759362,large_daughter
36,1578,603.761,629.853,148.510,bud,33,0.0,202.551,0.733198,large_daughter
37,1947,901.882,639.78,165.338,mother,34,0.0,133.196,0.805598,large_mother
38,2505,387.67,645.222,188.894,mother,35,0.0,143.439,0.759362,large_mother
39,2537,443.48,667.131,188.510,mother,42,0.0,148.024,0.785232,large_mother
40,3586,686.509,673.696,224.551,un,-,0.0,-,-,no_bud
41,2791,555.445,699.584,195.924,mother,43,0.0,170.61,0.870797,large_mother
42,1538,401.41,693.826,148.024,bud,39,0.0,188.51,0.785232,large_daughter
43,2101,504.161,706.89,170.610,bud,41,0.0,195.924,0.870797,large_daughter
44,2809,446.185,720.651,197.581,mother,45,1.0,196.652,0.995298,large_mother
45,2735,387.728,739.604,196.652,bud,44,1.0,197.581,0.995298,large_daughter
46,2943,190.225,756.484,202.551,mother,47,0.0,200.309,0.988931,large_mother
47,2875,139.532,786.914,200.309,bud,46,0.0,202.551,0.988931,large_daughter
48,1750,823.994,843.921,158.953,mother,49,0.0,124.125,0.780891,large_mother
49,1101,862.178,859.147,124.125,bud,48,0.0,158.953,0.780891,large_daughter
50,1921,829.45,887.644,163.539,un,-,0.0,-,-,no_bud
51,2011,228.806,962.739,169.338,-,-,0.0,-,-,-
52,1,-,-,1.000,bud,11,0.0,163.782,0.006106,small_daughter